const products = [
    {
      id: "jfhgbvnscs",
      name: "Honey jar",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "honey",
      price: 49.99,
      image: "./images/5 Healing Honey Infusions for a Healthy Life.jpg",
      sale: true,
      saleAmount: 15,
    },
    {
      id: "dfsdfsdfsdf",
      name: "Bougies candle",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "candle",
      price: 35.50,
      image: "./images/15 bougies parfumées à s'offrir pour l'hiver.png",
    },
    {
      id: "adfsdfsdx",
      name: "Leaf Herbal tea",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "tea",
      price: 23.99,
      image: "./images/5 Loose Leaf Herbal Tea Sampler Tea Party Favors Care - Etsy.jpg",
      sale: true,
      saleAmount: 7,
    },
    {
      id: "dfweaaaarv",
      name: "Sunflower",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "flower",
      price: 20,
      image: "./images/25 Beautiful Flower Wallpapers For iPhone (Free Download!).png",
    },
    {
      id: "dfwfesarv",
      name: "Little honey",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "honey",
      price: 22.50,
      image: "./images/30 Cheap DIY Wedding Favors You Can Make Yourself.jpg",
    },
    {
      id: "dfwfebfrv",
      name: "Christmas gift",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "gift",
      price: 120,
      image: "./images/A Christmas Gift Guide with a Difference_ — Alice in Scandiland.jpg",
      sale: true,
      saleAmount: 50,
    },
    {
      id: "dfwfxverv",
      name: "Ceramic plate",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "ceramic",
      price: 100,
      image: "./images/Artist Uses Real Found Flowers to Create Delicate One-of-a-Kind Ceramics.png",
    },
    {
      id: "dfwfrweerv",
      name: "Cactus candle",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "candle",
      price: 24.40,
      image: "./images/b36b00f4-25e1-4ae2-ad09-2180d2c23152.jpg",
    },
    {
      id: "dfddffawferv",
      name: "Best S'mores Cookies",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "cookies",
      price: 26.20,
      image: "./images/Best S'mores Cookies - House of Nash Eats.png",
      sale: true,
      saleAmount: 6.20,
    },
    {
      id: "dfwfefzdsfsdrv",
      name: "Pack od mini cookies",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "cookies",
      price: 30,
      image: "./images/Bite-Sized Chocolate Chip Cookies.jpg",
    },
    {
      id: "dfwhfhferv",
      name: "Blue candle",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "candle",
      price: 17.50,
      image: "./images/Blue Moon Candle Project _ BrambleBerry.jpg",
    },
    {
      id: "dfytrwferv",
      name: "White flower",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "flower",
      price: 15,
      image: "./images/Cake Atelier Amsterdam - Katie Considers.jpg",
    },
    {
      id: "dfwhgfdsferv",
      name: "Handmade bath gift",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "gift",
      price: 190,
      image: "./images/Candle & Match Striker Gift Set - Handmade, Small batch natural soy tumbler jar candle - 11_8 oz.jpg",
    },
    {
      id: "xcvbndfwferv",
      name: "Sukulent candle",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "cookies",
      price: 20,
      image: "./images/Candle Making Supplies List for Beginners _ BrambleBerry.png",
    },
    {
      id: "dzxcvbnfwferv",
      name: "Ceramic flower Mug",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "ceramic",
      price: 130.99,
      image: "./images/Ceramic Mug Turkish Mug Handmade Ceramic Coffee Mug - Etsy.jpg",
    },
    {
      id: "qwertydfwferv",
      name: "Creamy Latte",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "coffee",
      price: 40,
      image: "./images/Creamy Cashew Gingersnap Lattes {vegan}.jpg",
    },
    {
      id: "dwertyfwferv",
      name: "Ceramic Mug",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "ceramic",
      price: 170,
      image: "./images/d8e0d9c3-6ea6-40c6-a99f-b4e167282fdf.jpg",
    },
    {
      id: "asdfghdfwferv",
      name: "A few cookies with chocolate",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "cookies",
      price: 50,
      image: "./images/Damn Good Paleo Chocolate Chunk Tahini Cookies _ Ambitious Kitchen.jpg",
    },
    {
      id: "dsdfghfwferv",
      name: "Żonkile flowers",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "flower",
      price: 60.50,
      image: "./images/dedb6d3f-a915-4ca0-b82c-7bea3a264332.jpg",
    },
    {
      id: "dfwfsdfgherv",
      name: "Candle in glass",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "candle",
      price: 130,
      image: "./images/DIY Lavender Essential Oil Candles 💜 Easy Homemade Soy Candle Recipe for Sleep + Relaxation.jpg",
    },
    {
      id: "dfwffgnerv",
      name: "Basket - warm time",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "gift",
      price: 330,
      image: "./images/Easy Christmas Gift Baskets Ideas DIY.webp",
      sale: true,
      saleAmount: 80,
    },
    {
      id: "dfwfehgvcrv",
      name: "Pack of tea",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "tea",
      price: 100,
      image: "./images/packoftea.png",
    },
    {
      id: "dfwferhgv",
      name: "Pink flowers",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "flower",
      price: 93,
      image: "./images/February Member Make_ Crepe Paper Coral Supreme Peony.jpg",
    },
    {
      id: "dfwfehgrfedrv",
      name: "Bouqet",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "flower",
      price: 130.99,
      image: "./images/Flower photography tips and ideas by Eva Nemeth - From Britain with Love.jpg",
    },
    {
      id: "dfwfesfwrv",
      name: "Honey in glass",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "honey",
      price: 70,
      image: "./images/Food and Recipes _ Southern Living.jpg",
      sale: true,
      saleAmount: 20,
    },
    {
      id: "dfwfejtyjtrv",
      name: "Tea in glass",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "tea",
      price: 130,
      image: "./images/Gift Collections — Mother Mountain.jpg",
    },
    {
      id: "dfwfervjytj",
      name: "Colorfull ceramic plate",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "ceramic",
      price: 110,
      image: "./images/Hana Karim on Instagram_ “My ultimate summer palette in one photo ☀️ Setting up t.jpg",
    },
    {
      id: "dfwferjtyjtv",
      name: "Flowers ceramic plate",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "ceramic",
      price: 130,
      image: "./images/Handmade Ceramic Plate With a Flowers Pottery Dinnerware - Etsy.png",
      sale: true,
      saleAmount: 30,
    },
    {
      id: "dfwadaferv",
      name: "Cookies with jam heart",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "cookies",
      price: 40,
      image: "./images/Heart-shaped Jam Thumbprint Cookies _ wanna come with_.png",
      sale: true,
      saleAmount: 10,
    },
    {
      id: "dfwfxcvvserv",
      name: "Bubble candle",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "candle",
      price: 30,
      image: "./images/Her er stearinlystrenden, der kommer efter de snoede lys.png",
    },
    {
      id: "dfwdfgdfgferv",
      name: "Little Honey Drops",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "honey",
      price: 55,
      image: "./images/Homemade Honey Lemon Ginger Throat Drops.jpg",
    },
    {
      id: "dasfsfsfwferv",
      name: "Honey Soap",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "honey",
      price: 25,
      image: "./images/Honey & Oatmeal Soap.jpg",
      sale: true,
      saleAmount: 5,
    },
    {
      id: "avbdgddfwferv",
      name: "Blue Flowers",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "flower",
      price: 35,
      image: "./images/How to Grow Forget-Me-Nots at Home in a Pot _ Hunker.jpg",
    },
    {
      id: "adasddfwferv",
      name: "Iced Latte",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "coffee",
      price: 30.99,
      image: "./images/iced latte.jpg",
      sale: true,
      saleAmount: 9.99,
    },
    {
      id: "dfwferzxcv",
      name: "Chocolate Cookies",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "cookies",
      price: 30,
      image: "./images/Innen weich, außen knusprig_ super einfache Schoko-Cookies - Herbs & Chocolate.png",
    },
    {
      id: "dfwfekhjkrv",
      name: "Lavenda Candle",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "candle",
      price: 25.99,
      image: "./images/Lavender Crown Pillar Soy Candles, Natural Flower Candle,Botanical Candles,Cotton or Wooden Wick,Beautiful Wedding Decorations_.jpg",
    },
    {
      id: "dfwfecbcvbrv",
      name: "Blueberry cookies",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "cookies",
      price: 32,
      image: "./images/Lemon Blueberry Cookies.jpg",
    },
    {
      id: "dfwfgdfgderv",
      name: "Lemon Cookies",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "cookies",
      price: 30,
      image: "./images/Lemon Sugar Cookies.jpg",
    },
    {
      id: "dfwsrtrferv",
      name: "Lovely Smoth Box",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "gift",
      price: 350,
      image: "./images/Loved and Found _ Custom and Curated Gift Boxes.jpg",
      sale: true,
      saleAmount: 50,
    },
    {
      id: "dfwfdzgrzrerv",
      name: "Raspberry Cookies",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "cookies",
      price: 35,
      image: "./images/Raspberry ripple cookies recipe _ Sainsbury`s Magazine.png",
    },
    {
      id: "dfwffgnerv",
      name: "Coffee Candle",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "candle",
      price: 60,
      image: "./images/Sabonetes coloridos para o Dia das Mães - Como fazer em casa.jpg",
    },
    {
      id: "dfwferzjv",
      name: "Ceramic Coasters",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "ceramic",
      price: 90,
      image: "./images/SMOC_ Handmade Ceramic Fruit Coasters - Set of 4.png",
    },
    {
      id: "dfwfebsrv",
      name: "Green Gift",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "gift",
      price: 30,
      image: "./images/Tea Forte Fleur Gift Set.jpg",
    },
    {
      id: "dfwhfgferv",
      name: "Little turtle ceramic",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "ceramic",
      price: 39.99,
      image: "./images/Самодельные глиняные горшочки для растений 🐢.jpg",
      sale: true,
      saleAmount: 10,
    },
    {
      id: "dfwfererv",
      name: "Little Honey",
      description: `Lorem ipsum dolor sit amet consectetur adipisicing elit. Quod,
      dolores eaque. Eligendi ab officia minus.`,
      category: "honey",
      price: 20,
      image: "./images/🐝How to Hold Your Honey - An Adorable Collection of Bee & Beehive Honey Pots.jpg",
    },
  ];
  